### ISSUE TITLE
Loding Master Node & Storage Listener

### ISSUE THREAD

**Issue by Cftn** [cyber-geiger/toolbox-storage#40]
Actually, I tested with Android Phone not on Mac OS.  
It has been working well before the update to the 0.6.25 new version.

1. Can't load the master Node using GEIGER API.
>>It should create the storage as SQLite (that means create Master Node themselves) before calling the GEIGER API to get the Master node. It had not been required before.

![image](https://user-images.githubusercontent.com/15152117/153933022-86eff233-aca0-4356-8f26-0fe4166d861f.png)

2. The listener only works inside each plugin, not connection with the others using GEIGER API.
>>  It does not work if I get the controller (Master node) using GEIGER API. It only works well delivering the controller (Master node) as a parameter, I tested it using two different plugins.
>> Would you please share the listener example of interacting connections (two files, sender and receiver )? I checked a new example but it only considered aspects of independence I think.
It should consider multiple connections such as two Android apps (GEIGER tool-box and GEIGER indicator, not only one App (GEIGER tool-box).

**Comment by luongnv89** [comment]
I don't fully understand the context of this issue. But I think the problem with the permission have been resolved long time ago.

**Comment by Cftn** [comment]
Unfortunately, this error happened when load the indicator as package which is include new version 0.6.27 of local storage. 
It is works well below 0.6.25 version.
The listener is still not work.

**Comment by martingwerder** [comment]
We probably found a bug and fixed it in 0.6.29. Can anyone of the reporters confirm that the issue on android is gone?

**Comment by Cftn** [comment]
Thanks a lot for your contributions.
I am doing the test on Android but the LDS is empty, therefore I cannot get default data such as 'Local:Plugin' which has the current User/Device ID.

However it worked well and there is data when I tested on Indicator using Dart testing, not integrated with UI.

**Comment by luongnv89** [comment]
I can confirm that in the version 0.6.30, the external plugin is no longer able to get current Device/User ID, thus impossible for an external plugin to make a change in local storage which make it impossible to test if the Master Plugin can listen to the Storage Event

**Comment by martingwerder** [comment]
I am sorry but you completely loose me. I do not understand where tehe problems are. 

The texts provided above require a context I do not seem have and MWEs are a pure luxury. As an immediate result I am unable to solve a bug as I do not know what the bug is. 

Unless someone is able to give some meaningful context within and steps to reproduce the problem a day, I will close this issue and ask anyone to open a new one describing the problems (with MWE).

**Comment by luongnv89** [comment]
I have created a proper issue for this bug, please refer to this issue #41
